# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 849038a1279e7b9c09f87fbba0adb6e3b9d162f549b7c259792bb8c4d68ee2501c51cac9a1a191e5622f869947e102d50e1c95ec7d847ea7a54e7190ade5ef67

test:
  secret_key_base: 110674e4f7662e31549df1f04dfdf5d81ce89bd63b9481a04dcc569cbfc9d836db1a13469b0028d96ed758cdbe32b555fa1f92d4db24acd053fa347eaed1043e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
